"""
Pydantic schemas for API validation.
"""

from app.schemas.competitor import (
    CompetitorBase,
    CompetitorCreate,
    CompetitorUpdate,
    CompetitorInDB,
    CompetitorResponse,
    CompetitorActivityBase,
    CompetitorActivityCreate,
    CompetitorActivityUpdate,
    CompetitorActivityInDB,
    CompetitorActivityResponse,
    CompetitorProductBase,
    CompetitorProductCreate,
    CompetitorProductUpdate,
    CompetitorProductInDB,
    CompetitorProductResponse,
    CompetitorNewsBase,
    CompetitorNewsCreate,
    CompetitorNewsUpdate,
    CompetitorNewsInDB,
    CompetitorNewsResponse,
)

from app.schemas.market import (
    MarketTrendBase,
    MarketTrendCreate,
    MarketTrendUpdate,
    MarketTrendInDB,
    MarketTrendResponse,
    MarketSegmentBase,
    MarketSegmentCreate,
    MarketSegmentUpdate,
    MarketSegmentInDB,
    MarketSegmentResponse,
    MarketIntelligenceBase,
    MarketIntelligenceCreate,
    MarketIntelligenceUpdate,
    MarketIntelligenceInDB,
    MarketIntelligenceResponse,
)

from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserInDB,
    UserResponse,
    UserLogin,
    Token,
    TokenPayload,
    ApiKeyBase,
    ApiKeyCreate,
    ApiKeyResponse,
)

from app.schemas.alert import (
    AlertBase,
    AlertCreate,
    AlertUpdate,
    AlertInDB,
    AlertResponse,
    AlertRuleBase,
    AlertRuleCreate,
    AlertRuleUpdate,
    AlertRuleResponse,
    SavedSearchBase,
    SavedSearchCreate,
    SavedSearchUpdate,
    SavedSearchResponse,
    ReportBase,
    ReportCreate,
    ReportUpdate,
    ReportResponse,
)

from app.schemas.common import (
    PaginationParams,
    PaginatedResponse,
    MessageResponse,
    HealthResponse,
    ErrorResponse,
)

__all__ = [
    # Competitor schemas
    "CompetitorBase",
    "CompetitorCreate",
    "CompetitorUpdate",
    "CompetitorInDB",
    "CompetitorResponse",
    "CompetitorActivityBase",
    "CompetitorActivityCreate",
    "CompetitorActivityUpdate",
    "CompetitorActivityInDB",
    "CompetitorActivityResponse",
    "CompetitorProductBase",
    "CompetitorProductCreate",
    "CompetitorProductUpdate",
    "CompetitorProductInDB",
    "CompetitorProductResponse",
    "CompetitorNewsBase",
    "CompetitorNewsCreate",
    "CompetitorNewsUpdate",
    "CompetitorNewsInDB",
    "CompetitorNewsResponse",
    
    # Market schemas
    "MarketTrendBase",
    "MarketTrendCreate",
    "MarketTrendUpdate",
    "MarketTrendInDB",
    "MarketTrendResponse",
    "MarketSegmentBase",
    "MarketSegmentCreate",
    "MarketSegmentUpdate",
    "MarketSegmentInDB",
    "MarketSegmentResponse",
    "MarketIntelligenceBase",
    "MarketIntelligenceCreate",
    "MarketIntelligenceUpdate",
    "MarketIntelligenceInDB",
    "MarketIntelligenceResponse",
    
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserInDB",
    "UserResponse",
    "UserLogin",
    "Token",
    "TokenPayload",
    "ApiKeyBase",
    "ApiKeyCreate",
    "ApiKeyResponse",
    
    # Alert schemas
    "AlertBase",
    "AlertCreate",
    "AlertUpdate",
    "AlertInDB",
    "AlertResponse",
    "AlertRuleBase",
    "AlertRuleCreate",
    "AlertRuleUpdate",
    "AlertRuleResponse",
    "SavedSearchBase",
    "SavedSearchCreate",
    "SavedSearchUpdate",
    "SavedSearchResponse",
    "ReportBase",
    "ReportCreate",
    "ReportUpdate",
    "ReportResponse",
    
    # Common schemas
    "PaginationParams",
    "PaginatedResponse",
    "MessageResponse",
    "HealthResponse",
    "ErrorResponse",
]